version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  cart-service:
    build:
      context: ./cart-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - SPRING_REDIS_HOST=redis
    depends_on:
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SERVICE_CART_URL=http://cart-service:8082
    depends_on:
      - cart-service


volumes:
  redis_data: